name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

permissions:
  contents: read

jobs:
  lint-test:
    runs-on: ubuntu-latest
    env:
      UV_VERSION: "0.8.17"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install UV
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Ruff lint
        run: uv run ruff check

      - name: Ruff format
        run: uv run ruff format --check

      - name: Mypy
        run: uv run mypy src

      - name: Pytest
        run: uv run pytest -vv

  docker-build:
    runs-on: ubuntu-latest
    needs: lint-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build --file Dockerfile .
